### ISSUE TITLE
Movie search bug

### ISSUE THREAD

**Issue by zacharywasielewski** [zacharywasielewski/MovieAnalytics#24]

**Comment by zacharywasielewski** [comment]
movie.search('Star Wars')
-----------------------------------------------

Traceback (most recent call last):

  File "<ipython-input-13-e9bb5ba30af2>", line 1, in <module>
    runfile('C:/Users/G672594/.spyder-py3/Movie Scrape.py', wdir='C:/Users/G672594/.spyder-py3')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/G672594/.spyder-py3/Movie Scrape.py", line 267, in <module>
    df = create_df(ratings, genre_dict)

  File "C:/Users/G672594/.spyder-py3/Movie Scrape.py", line 92, in create_df
    search = movie.search(search_title) #search for movies by title

  File "C:\ProgramData\Anaconda3\lib\site-packages\tmdbv3api\objs\movie.py", line 224, in search
    "query=" + quote(term) + "&page=" + str(page),

  File "C:\ProgramData\Anaconda3\lib\site-packages\tmdbv3api\tmdb.py", line 156, in _call
    json = req.json()

  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)

  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

**Comment by zacharywasielewski** [comment]
Fixed by adding a dict called 'movie_title_map' to change the title of the failing movie
